TitlePane.unifiedBackground=false

TitlePane.background=#1F3A77
TitlePane.foreground=#FFFFFF

TitlePane.buttonHoverBackground=#ACC813
TitlePane.buttonHoverForeground=#FFFFFF
TitlePane.buttonSize=35,23